name: Blockbattles
version: '${project.version}'
main: dev.cregg.blockbattles.Blockbattles
api-version: 1.19
libraries:
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.10.0
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-core:2.10.0
commands:
  duel:
    description: Request a duel
    usage: /duel <username>
    permission:
  reloadlua:
    description: Reload lua
    usage: /reloadlua
    permission:
  blockdeck:
    description: Configure your block battles deck
    usage: /blockdeck
    permission:
  rules:
    description: Get rules
    usage: /rules
    permission:
  version:
    description: Get jar version
    usage: /version
    permission:


